name:                AssignmentForReal
version:             0.1.0.0
github:              "githubuser/AssignmentForReal"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AssignmentForReal#readme>

dependencies:
- base >= 4.7 && < 5
- random
- HUnit

library:
  source-dirs: src

executables:
  AssignmentForReal-exe:
    main:                Eliza.hs
    source-dirs:         app
    dependencies:
    - AssignmentForReal

tests:
  AssignmentForReal-test:
    main:                ChatterbotTest.hs
    source-dirs:         test
    dependencies:
    - AssignmentForReal
